app = "bugtracker-app" # Give your app a unique name on Fly.io

primary_region = "bom"

[build]
  # If you're using Maven and your Spring Boot is inside `src`, change this
  builder = "paketobuildpacks/builder:base"

[env]
  SERVER_PORT = "8080"
  SPRING_PROFILES_ACTIVE = "prod"
  SPRING_DATA_MONGODB_URI = "${MONGODB_URI}"  # Use `fly secrets` to set this

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_threshold = 3
